apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: modulo-5
  namespace: diplomado
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: modulo-5
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50